# Generated by Django 4.0.3 on 2022-09-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('category', models.CharField(max_length=10)),
                ('lectureId', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=10)),
                ('totalCredits', models.IntegerField()),
                ('nonTotalCredits', models.IntegerField()),
                ('practiceCredits', models.IntegerField()),
                ('time', models.CharField(max_length=10)),
                ('room', models.CharField(max_length=10)),
                ('professor', models.CharField(max_length=10)),
                ('campus', models.BooleanField(max_length=10)),
                ('note', models.CharField(max_length=10)),
            ],
        ),
    ]
