# Generated by Django 4.0.3 on 2022-09-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='campus',
            field=models.BooleanField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='category',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='lectureId',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='note',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='professor',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='room',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='time',
            field=models.CharField(max_length=1000),
        ),
    ]
