# Generated by Django 4.0.3 on 2022-09-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0005_alter_lecture_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='naote',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
