# Generated by Django 4.0.3 on 2022-09-23 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0006_lecture_naote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='naote',
        ),
    ]
