# Generated by Django 4.0.3 on 2022-09-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0007_remove_lecture_naote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='age',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='campus',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='nonTotalCredits',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='practiceCredits',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='totalCredits',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
